### ISSUE TITLE
is it done? can i try it ?

### ISSUE THREAD

**Issue by mote166** [ElektroPrinz/MasterBuilders#2]

**Comment by LegoFan48737** [comment]
Yea I'd like to know as well ^^

**Comment by mote166** [comment]
@LegoFan48737 have u tried it?

**Comment by LegoFan48737** [comment]
If I have, I don't remember. I'll check over the code soon, and maybe fork it and translate it to English. @mote166

**Comment by 2cool4u567** [comment]
u doneeeeeeeeee!?

**Comment by 2cool4u567** [comment]
@LegoFan48737

**Comment by LegoFan48737** [comment]
@2cool4u567 Oof, forgot about this and no, I never started. You'll havta wait for @ElektroPrinz to do it, I'm working on a new Anarchy server, and I honestly don't have the time or patience to fiddle around with this.

**Comment by mote166** [comment]
i will close this issue since i already found an old plugin for this game and updated it and no longer need this.
